### ISSUE TITLE
Importing scikits.cuda.misc module under Windows gives runtime error

### ISSUE THREAD

**Issue by tenor27** [lebedov/scikits.cuda#104]
Sort of similar to #18; I needed the scikits.cuda.linalg module for dot product, running Windows 7 with scikits.cuda 0.5 b1 installed.  The linalg module imports the scikits.cuda.misc module, which in turn uses magma.py to check if the magma libraries are installed. If I'm running Linux or Mac OS X and DON'T have the magma libraries, the check returns an OSError and continues the original import without initializing the magma library. If I'm running Windows, the magma check returns a RuntimeError('unsupported platform') and does not attempt the import. I modified line no. 19~20 in magma.py to read:
    
    elif sys.platform == 'win32':
        raise OSError('Windows does not have Magma')

The original import of scikits.cuda.linalg continues after this, just without attempting to initialize the nonexistent magma libraries. The linalg.dot function appears to work as expected. I am not familiar enough with GitHub protocol to know if this is the proper way to report a potential bug and a potential workaround, so I apologize if this is an incorrect method.

**Comment by lebedov** [comment]
It's actually preferable for the code to try to load the shared library for Windows and fail gracefully; I modified `magma.py` to do so. Let me know (via GitHub) if you encounter further issues.

**Comment by tenor27** [comment]
Alright; thank you muchly.
