### ISSUE TITLE
Overwrite parameter in linalg functions doesn't have consistent default

### ISSUE THREAD

**Issue by untom** [lebedov/scikits.cuda#110]
Hi!

I was burned badly by a bug today because `skcuda.linalg.dot_diag` has a parameter `overwrite` that is `True` by default. It took me quite some time to notice that I destroyed a matrix that I still needed. In fact, many of the functions in `linalg` have a default of `overwrite=True`, but not all of them. I'm guessing most functions I added have overwrite=False, while most of yours have overwrite=True.

Overwriting=False is the default in numpy and scipy. Of course this is less efficient (though maybe that performance can be saved by activating the memory pool) and creates an issue with legacy code.  However, I think that having a "safer" default (i.e., `overwrite=False`) makes more sense than a highly optimized one.  Which is why I'd argue to change the defaults to `False`.  What do you think?

**Comment by hainm** [comment]
I agree to use default `fault` value. It's kind of dangerous.

**Comment by untom** [comment]
@hainm: I think a small formatting error crept in your reply: which default value do you agree to use? `True` or `False`?

**Comment by lebedov** [comment]
No objections, although I suggest that all of the docstrings also be updated to explicitly include the default value (even if we do make it consistent across all functions with an overwrite param). @untom, can you make this change? Feel free to credit yourself in the changelog :-)

**Comment by hainm** [comment]
@untom hi, I just fixed

**Comment by untom** [comment]
Sure, I'll change it

**Comment by lebedov** [comment]
Thanks.
